### ISSUE TITLE
thank you!

### ISSUE THREAD

**Issue by MEOW-TYMX** [dsmaynard/fungal_biogeography#2]
Hello! Could you please tell me what  is  'matric_pot' in 'moisture curve'  mean? thanks for help us a lot!

**Comment by dsmaynard** [comment]
Hi - this is "matric potential". It's a measure of the moisture availability in the agar, as modified using KCl.

Cheers,
Dan

**Comment by MEOW-TYMX** [comment]
Thank you for your help!
